require 'modalsupport'

require "numerals/version"
require 'numerals/numeral'
require 'numerals/rounding'
require 'numerals/conversions/float'
require 'numerals/conversions/integer'
require 'numerals/conversions/rational'
require 'numerals/conversions/bigdecimal'
require 'numerals/conversions/flt'
require 'numerals/format/aspect'
require 'numerals/format/mode'
require 'numerals/format/exp_setter'
require 'numerals/format/base_scaler'
require 'numerals/format/text_parts'
require 'numerals/format/symbols'
require 'numerals/format/output'
require 'numerals/format/input'
require 'numerals/format/assembler'
require 'numerals/format'
# require 'numerals/formatting/options'
